export default {
	"text-font": "sans-serif",
	"bg": "transparent",
	"highlight-color": "#ffcc00",
	"secondary-color": "#ffec99",
	"order": "row",
	"clue-width": "16em",
	"clue-text-font": "var(--text-font, sans-serif)",
	"clue-text-color": "#1a1a1a",
	"clue-scrollbar-bg": "#efefef",
	"clue-scrollbar-fg": "#cdcdcd",
	"puzzle-border-color": "#1a1a1a",
	"cell-bg-color": "#fff",
	"cell-border-color": "#1a1a1a",
	"cell-void-color": "#1a1a1a",
	"cell-border-width": "0.01",
	"cell-text-font": "var(--text-font, sans-serif)",
	"cell-text-color": "#1a1a1a",
	"cell-text-size": "0.7em",
	"cell-text-weight": "700",
	"number-text-size": "0.3em",
	"number-text-weight": "400",
	"number-text-color": "#6a6a6a",
	"toolbar-text-font": "var(--text-font, sans-serif)",
	"toolbar-text-size": "0.85em",
	"toolbar-bg": "transparent",
	"toolbar-button-bg": "#efefef",
	"toolbar-button-bg-hover": "#cdcdcd",
	"toolbar-button-padding": "0.75em",
	"toolbar-button-border": "none",
	"toolbar-button-border-radius": "4px",
	"toolbar-button-text-color": "#6a6a6a",
	"toolbar-button-text-weight": "400",
	"message-text-font": "sans-serif",
	"message-text-size": "0.85em",
	"message-bg": "transparent",
	"message-button-bg": "#efefef",
	"message-button-bg-hover": "#cdcdcd",
	"message-button-padding": "0.75em",
	"message-button-border": "none",
	"message-button-border-radius": "4px",
	"message-button-text-color": "#6a6a6a",
	"message-button-text-weight": "400",
};
